title:            I am Miguel Julián -  I love writing & coding & much more
tagline:          Because change happens!
description:      I am gonna be adding to this page those things I write
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://www.migueljulian.com
#url:              http://localhost:4000
navigation:       false

# Owner/author information
owner:
  name:           Miguel Julián
  avatar:         bio-photo.jpg
  bio:            "Sometimes I may also be known as Miky or figarocorso.<br /><br />I am currently working at Frogtek as QA engineer / DevOps.<br /><br />Welcome to the Cow Land!"
  email:
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        miky_kun
  facebook:       migueljulian
  github:         figarocorso
  linkedin:       migueljulian
  instagram:      miky_kun
  lastfm:         figarocorso
  tumblr:
  hmfaysalsocial:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Artículos
    url: /articles/
  - title: Relatos
    url: /short-stories/
  - title: "\' Day by day \' blog"
    url: /blog/
  - title: "Genbeta"
    url: /genbeta/
  - title: "Music reviews"
    url: /music-review/
#  - title: T-Details
#    url: /technical-details/
#  - title: The Evil-Genius
#    url: http://www.theevilgenius.tk/
#    external: true

projects:
    - title: Autofocus blog
      url: /blog/
      description: "Blog personal donde busco automotivarme para no caer en la rutina del día a día. También he incluido en esta sección los artículos recuperados del blog 'bipersonal' dosidiotas.com, a partir de 2010 los posts pertenecían a este blog (se aprecia cambio en el estilo)."
    - title: Artículos
      url: /articles/
      description: "Artículos que han sido publicados por diversos medios."
    - title: Relatos
      url: /short-stories/
      description: "Algunos relatos cortos de diferente temática. Sangre, amor, aventuras... sigo recopilando algunos."
    - title: Críticas (reviews) de música
      url: /music-review/
      description: "Críticas sobre discos o conciertos recuperados de Rockthunder y Metalthunder."
    - title: Genbeta
      url: /genbeta/
      description: "Artículos escritos en la página Genbeta.com. (290 noticias publicadas)."

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid
future:      true
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:day/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
